### ISSUE TITLE
Code review: Componenten benamning

### ISSUE THREAD

**Issue by iBadr49** [zenitba/FDNDStrandeiland#39]
Ik zou de benaming van de componenten consistent houden en alles in het Engels schrijven.

**Comment by iBadr49** [comment]
<img width="276" alt="Scherm­afbeelding 2024-03-21 om 12 04 26" src="https://github.com/zenitba/FDNDStrandeiland/assets/112857932/49162489-9630-43fc-9063-cd037fcf5792">

**Comment by zenitba** [comment]
**Componenten namen veranderd**
<img width="140" alt="Schermafbeelding 2024-03-21 om 20 53 17" src="https://github.com/zenitba/FDNDStrandeiland/assets/112856019/643ee92e-e93a-4fe8-94bf-62cb33d279a9">
**Dankkje voor je feedback👍**
