### ISSUE TITLE
Sprint review 21/03/2024

### ISSUE THREAD

**Issue by MokhtarAkle** [zenitba/FDNDStrandeiland#41]
- Veel witruimte bij overzicht pagina wensen, probeer dit op te vullen met tekst of een foto
- Filter stijl in lijn brengen met de rest van de pagina, dialog kunnen sluiten door buiten het scherm te klikken
- Font van datums aanpassen gebaseerd op de rest van de site
- SVG's proberen apart in je assets te zetten en op te halen
- Probeer de vele `<div>` elementen te vervangen voor semantisch correcte elementen waar mogelijk.
- `<input>` elementen moeten in een `<form>` element voor semantische HTML https://github.com/zenitba/FDNDStrandeiland/blob/70a047afe1b039abc4e033b08222967fd6c85715/src/lib/components/Navbar.svelte#L11

**Comment by zenitba** [comment]
- [x] Veel witruimte bij overzicht pagina wensen, probeer dit op te vullen met tekst of een foto
**Opgevuld.**
<img width="440" alt="Schermafbeelding 2024-03-24 om 19 03 42" src="https://github.com/zenitba/FDNDStrandeiland/assets/112856019/0a8f5f34-ebaf-4017-a76b-79e09bd82283">

- [x] Filter stijl in lijn brengen met de rest van de pagina, dialog kunnen sluiten door buiten het scherm te klikken
```html
<button class="overlay" on:click={togglePopup}></button>
```
<img width="442" alt="Schermafbeelding 2024-03-24 om 19 43 28" src="https://github.com/zenitba/FDNDStrandeiland/assets/112856019/e8fd7ea6-43f8-4216-9c72-4741d274b0ef">

- [x] Font van datums aanpassen gebaseerd op de rest van de site
```css
font-weight: 500;
```
<img width="209" alt="Schermafbeelding 2024-03-24 om 19 44 06" src="https://github.com/zenitba/FDNDStrandeiland/assets/112856019/c2161c59-5604-4f8d-9d23-d2b09e1fc2d5">
