### ISSUE TITLE
Code review: Carrousel zonder JS

### ISSUE THREAD

**Issue by iBadr49** [zenitba/FDNDStrandeiland#42]
Als JavaScript is uitgeschakeld, kun je misschien de schuifbalk of de volgende slide tonen om te laten zien dat er andere slide's beschikbaar zijn.

**Comment by zenitba** [comment]
**Toegevoegde Code:**
```js
// Zorg ervoor dat de carousel informatie button niet zichtbaar is waneer JS ingeschakeld is
  onMount(() => {
    const carouselElements = document.querySelectorAll('.carousel-info-button');
    carouselElements.forEach(function(element) {
      element.style.display = 'none';
    });
  });
```
```html
<!-- Knop voor informatie over carousel als JS uit staat -->
<button class="carousel-info-button">
    Scroll voor de volgende slide
</button>
```

<img width="436" alt="Schermafbeelding 2024-03-24 om 19 48 02" src="https://github.com/zenitba/FDNDStrandeiland/assets/112856019/756a20df-afb4-4e4c-9e57-5c0a316708ea">
